# Generated by Django 5.0.6 on 2024-07-29 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Value')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cash Balance')),
                ('investments_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Investments Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Portfolio Value',
                'verbose_name_plural': 'Portfolio Values',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='stats_portf_user_id_325cae_idx')],
                'unique_together': {('user', 'timestamp')},
            },
        ),
    ]
