# SETTINGS FILE EXTENDED FOR PRODUCTION
from config.settings import *
from decouple import config

DEBUG = False
ALLOWED_HOSTS = ['*']

SECURE_HSTS_SECONDS = 3600
SECURE_SSL_REDIRECT = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

