# Generated by Django 5.0.3 on 2024-04-29 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date Modified')),
                ('investment_type', models.CharField(max_length=10, verbose_name='Investment Type')),
                ('investment_symbol', models.CharField(max_length=10, verbose_name='Investment Symbol')),
                ('investment_name', models.CharField(max_length=100, verbose_name='Investment Name')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investment Quantity')),
                ('average_trade_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Trade Price')),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission')),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Basis')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Price')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Value')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P&L')),
                ('profit_loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P&L %')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Portfolio Entry',
                'verbose_name_plural': 'Portfolio Entries',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction Date')),
                ('investment_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('cash', 'Cash')], max_length=10, verbose_name='Investment Type')),
                ('investment_symbol', models.CharField(max_length=10, verbose_name='Investment Symbol')),
                ('investment_name', models.CharField(max_length=100, verbose_name='Investment Name')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Cash Deposit'), ('withdrawal', 'Cash Withdrawal')], max_length=10, verbose_name='Transaction Type')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('trade_price', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trade Price')),
                ('commission', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
