# Generated by Django 5.0.6 on 2024-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_user_remove_stocktransaction_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtransaction',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto')], max_length=10, verbose_name='Transaction Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(verbose_name='Transaction Date'),
        ),
    ]
