# Generated by Django 5.0.3 on 2024-04-30 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_investment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='trade_price',
            field=models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trade Price'),
        ),
    ]
