# Generated by Django 5.0.3 on 2024-04-18 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_price',
            field=models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trade Price'),
        ),
    ]
