# Generated by Django 5.0.6 on 2024-07-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_investment_type_portfolioentry_investment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioentry',
            old_name='investment_category',
            new_name='investment_type',
        ),
    ]
