# Generated by Django 5.0.3 on 2024-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_transaction_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Price'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Value'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit/Loss'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='profit_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profit/Loss %'),
        ),
        migrations.DeleteModel(
            name='PortfolioSnapshot',
        ),
    ]
