# Generated by Django 5.0.3 on 2024-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolioentry_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('cash', 'Cash')], max_length=10, verbose_name='Instrument Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('cash', 'Cash')], max_length=10, verbose_name='Instrument Type'),
        ),
    ]
