# Generated by Django 5.0.6 on 2024-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_investment_category_portfolioentry_investment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='average_trade_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Trade Price'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='commissions',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='cost_basis',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Cost Basis'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='current_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='current_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='investment_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Investment Name'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='investment_symbol',
            field=models.CharField(max_length=10, verbose_name='Investment Symbol'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='profit_loss',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='P&L'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='profit_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='P&L %'),
        ),
    ]
