# Generated by Django 5.0.3 on 2024-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_cash_balance_cashbalance_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cash Balance'),
        ),
    ]
