# Generated by Django 5.0.3 on 2024-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_cashbalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='average_trade_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Trade Price'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost Basis'),
        ),
    ]
