# Generated by Django 5.0.3 on 2024-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_portfolio_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='investment_name',
            field=models.CharField(default='', max_length=100, verbose_name='Investment Name'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='investment_symbol',
            field=models.CharField(default='', max_length=10, verbose_name='Investment Symbol'),
        ),
    ]
